export const LANG_MK_NAME = 'mk';

export const LANG_MK_TRANS = {
    'welcome' : 'Добредојдовте',
    'orders' : 'Нарачки',
    'newOrder' : 'Нова нарачка',
    'tableOrder' : 'Табела со направени нарачки',
    'orderNo' : 'Бр. на нарачка',
    'supplier' : 'Добавувач',
    'issueDate' : 'Датум на издавање',
    'paymentDate' : 'Датум на плаќање',
    'checkForDelivery' : 'Одбери за испорака',
    'deliveryDate' : 'Датум на испорака',
    'submit' : 'Потврди',
    'cancel' : 'Откажи',
    'edit' : 'Промени',
    'delete' : 'Избриши',
    'delivery' : 'Достава',
    'areYouSure' : 'Дали сте сигурни?',
    'yes' : 'Да',
    'no' : 'Не',
    'goToRegistration': 'Регистрирај се',
    'goToLogin' : 'Најави се',
    'signIn' : 'Најави се',
    'email' : 'Корисничка сметка',
    'username' : 'Корисничко име',
    'password' : 'Лозинка',
    'passwordConfirmation' : 'Потврди лозинка',
    'incorrectUsernameOrPassword' : 'Погрешно корисничко име или лозинка.',
    'internalServerError' : 'Серверска грешка.',
    'signUp' : 'Регистрирај се',
    'login' : 'Најава',
    'registration' : 'Регистрација',
    'checkEmailAvailability': 'Дали е слободна корисничката сметка?',
    'checkUsernameAvailability': 'Дали е слободнo корисничкто име?',
    'emailRequiered' : 'Корисничката сметка е задолжителна.',
    'emailValid' : 'Корисничката сметка не е валидна.',
    'emailExist' : 'Корисничката сметка постои.',
    'usernameRequiered' : 'Корисничкото име е задолжително.',
    'usernameExist' : 'Корисничкото име постои.',
    'usernameMinLength' : 'Корисничкото име не смее да биде пократко од 6 карактери.',
    'usernameMaxLength' : 'Корисничкото име не смее да биде подолго од 32 карактери.',
    'passwordRequiered' : 'Лозинката е задолжителна.',
    'passwordMinLength' : 'Лозинката не смее да биде пократка од 8 карактери.',
    'passwordMaxLength' : 'Лозинката не смее да биде подолга од 32 карактери.',
    'passwordConfirmationRequiered' : 'Подврдата на лозинка е задолжителна.',
    'passwordConfirmationMinLength' : 'Потврдата за лозинка не смее да биде пократка од 8 карактери.',
    'passwordConfirmationMaxLength' : 'Потврдата за лозинка не смее да биде подолга од 32 карактери.',
    'passwordsEqual' : 'Лозинките мора да бидат исти.',
    'errors' : 'Грешки',
    'orderNoRequired' : 'Бр. на нарачка е задолжително поле.',
    'supplierRequired' : 'Добавувач е задолжително поле.',
    'issueDateRequired' : 'Датум на издавање е задолжително поле.',
    'paymentDateRequired' : 'Датум на плаќање е задолжително поле.',
    'deliveryDateRequired' : 'Датум на испорака е задолжително поле.',
    'usernameSize' : 'Должината на корисничкото име мора да биде помеѓу 6-32.',
    'passwordSize' : 'Должината на лозинката мора да биде помеѓу 8-32.',
    'hello' : 'Здраво',
    'signout' : 'Одјава',
    'itemCategory' : 'Категорија',
    'itemName' : 'Име',
    'quantity' : 'Количина',
    'unit' : 'Мерка',
    'pricePerUnit' : 'Единечна цена',
    'id' : 'ИД',
    'totalPrice' : 'Вкупна цена',
    'save': 'Зачувај',
    'enterOrder' : 'Најпрво внесете артикал.',
    'itemRequired' : 'Артикал е задолжително поле.',
    'quantityRequired' : 'Количината е задолжително поле.'
};
