export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'welcome' : 'Welcome',
    'orders' : 'Orders',
    'newOrder' : 'New order',
    'tableOrder' : 'Table with my orders',
    'orderNo' : 'Order No.',
    'supplier' : 'Supplier',
    'issueDate' : 'Issue Date',
    'paymentDate' : 'Payment Date',
    'checkForDelivery' : 'Check For Delivery',
    'deliveryDate' : 'Delivery Date',
    'submit' : 'Submit',
    'cancel' : 'Cancel',
    'edit' : 'Edit',
    'delete' : 'Delete',
    'delivery' : 'Delivery',
    'areYouSure' : 'Are you sure?',
    'yes' : 'Yes',
    'no' : 'No',
    'goToRegistration': 'Go To Registration Page',
    'goToLogin' : 'Go To Login Page',
    'signIn' : 'Sign in',
    'email' : 'Email',
    'username' : 'Username',
    'password' : 'Password',
    'passwordConfirmation' : 'Password Confirmation',
    'incorrectUsernameOrPassword' : 'Incorrect username or password.',
    'internalServerError' : 'Internal Server Error.',
    'signUp' : 'Sign Up',
    'login' : 'Sign In',
    'registration' : 'Sign Up',
    'checkEmailAvailability': 'Check Email Availability?',
    'checkUsernameAvailability': 'Check Username Availability?',
    'emailRequiered' : 'Email is required.',
    'emailValid' : 'Email is not valid.',
    'emailExist' : 'Email exist.',
    'usernameRequiered' : 'Username is required.',
    'usernameExist' : 'Username exist.',
    'usernameMinLength' : 'Username must be at least 6 characters long.',
    'usernameMaxLength' : 'Username cannot be more than 32 characters long.',
    'passwordRequiered' : 'Password is required.',
    'passwordMinLength' : 'Password must be at least 8 characters long.',
    'passwordMaxLength' : 'Password cannot be more than 32 characters long.',
    'passwordConfirmationRequiered' : 'Password Confirmation is required.',
    'passwordConfirmationMinLength' : 'Password Confirmation must be at least 8 characters long.',
    'passwordConfirmationMaxLength' : 'Password Confirmation cannot be more than 32 characters long.',
    'passwordsEqual' : 'Passwords must be equal.',
    'errors' : 'Errors',
    'orderNoRequired' : 'Order No. is required.',
    'supplierRequired' : 'Supplier is required.',
    'issueDateRequired' : 'Issue Date is required.',
    'paymentDateRequired' : 'Payment Date is required.',
    'deliveryDateRequired' : 'Delivery Date is required.',
    'usernameSize' : 'Username must be between 6-32 characters long.',
    'passwordSize' : 'Password must be between 8-32 characters long.',
    'hello' : 'Hello',
    'signout' : 'Sign Out',
    'itemCategory' : 'Item Category',
    'itemName' : 'Item Name',
    'quantity' : 'Quantity',
    'price' : 'Price',
    'id' : 'ID'
};
